import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Menu, X } from 'lucide-react';
import './style.css';

const pics={hero:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=2200&q=90',nyc:'https://images.unsplash.com/photo-1485738422979-f5c462d49f74?auto=format&fit=crop&w=1100&q=88',coast:'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=1100&q=88',canyon:'https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?auto=format&fit=crop&w=1000&q=88',city:'https://images.unsplash.com/photo-1538970272646-f61fabb3a8a2?auto=format&fit=crop&w=1000&q=88',california:'https://images.unsplash.com/photo-1515896769750-31548aa180ed?auto=format&fit=crop&w=1000&q=88',nashville:'https://images.unsplash.com/photo-1545419913-775e3e2a0b43?auto=format&fit=crop&w=1000&q=88',news1:'https://images.unsplash.com/photo-1444723121867-7a241cacace9?auto=format&fit=crop&w=900&q=88',news2:'https://images.unsplash.com/photo-1564399579883-451a5d44ec08?auto=format&fit=crop&w=900&q=88',news3:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=88',news4:'https://images.unsplash.com/photo-1473445361085-b9a07f55608b?auto=format&fit=crop&w=900&q=88'};
const nav=[['VUSAC 소개','#about'],['미주 여행 인사이트','#discover'],['회원 안내','#members'],['주요 사업','#business'],['뉴스룸','#news'],['자료실','#contact']];
const members=['AURORA TRAVEL','BLUE PEAK TOURISM','CLOUD JOURNEY','DISCOVERY KOREA','EASTAR TRAVEL','HORIZON TOURS','INTERPARK TRIPLE','KAL TOUR','LOTTE TOUR','MODE TOUR','MYREALTRIP CORPORATE','ONE STOP TRAVEL','PRIME PASS','RED CAP TOUR','SEOUL TRAVEL','SMART SERVE','TOURVIS KOREA','TRAVEL MAKERS','WORLD CONNECT','YB TOURS','888 TOUR','A-TOUR KOREA','BEST WAY TRAVEL','CUCK TRAVEL','DODAM TOUR','EURO EXPRESS','GLOBE PLAN','HANATOUR ITC','JINAIR TRAVEL','KRT','NAVER TRAVEL','NEXTTOUR','ONLINETOUR CO., LTD.','PARADISE TOUR','TOUR 2000','THE TOUR','WEBTOUR','WITH TOUR','YOUNG TOUR','ZEUS WORLD'];
function Logo(){return <a className="logo" href="#top"><span className="logo-v">V</span><span><b>USAC</b><small>VISIT USA COMMITTEE KOREA</small></span></a>}
function App(){const[open,setOpen]=useState(false);const[en,setEn]=useState(false);const labels=en?['VUSAC About','Travel Insights','Membership','Business','Newsroom','Resources']:nav.map(x=>x[0]);return <div className="site" id="top">
<header><Logo/><nav>{nav.map(([_,href],i)=><a href={href} key={href}>{labels[i]}</a>)}</nav><div className="header-tools"><button onClick={()=>setEn(!en)}><span className={!en?'active':''}>KO</span><span className={en?'active':''}>EN</span></button><button className="hamburger" onClick={()=>setOpen(!open)} aria-label="메뉴">{open?<X/>:<Menu/>}</button></div></header>
{open&&<div className="mobile-nav">{nav.map(([label,href])=><a href={href} onClick={()=>setOpen(false)} key={href}>{label}<ArrowRight/></a>)}</div>}
<main><section className="hero"><div className="hero-photo"/><div className="hero-panel"><div className="hero-copy"><h1>미국을<br/>만나는<br/><strong>새로운 방식</strong></h1><p>여행의 가능성을 연결합니다.</p></div><div className="scroll-note">SCROLL<span/></div></div><div className="hero-credit">© VISIT USA COMMITTEE KOREA</div></section>
<section className="about section" id="about"><div className="section-index red">01 <span>ABOUT</span></div><div className="about-copy"><h2>한국과 미국, 여행과 산업의<br/>더 큰 연결을 만들어갑니다.</h2><p>VUSAC(Visit USA Committee Korea)는 한국과 미국의 여행 교류와 관광 산업의 지속 가능한 성장을 위해 민간이 함께 설립한 비영리 협회입니다. 미국 여행에 대한 깊이 있는 정보와 인사이트를 제공하고, 여행업계와의 협력을 통해 새로운 기회를 창출합니다.</p><a className="line-link" href="#contact">VUSAC 소개 보기 <ArrowRight/></a></div><div className="about-images"><div className="about-photo photo-nyc"/><div className="about-photo photo-coast"/><div className="coordinates">36.7783° N<br/>119.4179° W</div></div></section>
<section className="discover section" id="discover"><div className="section-head"><div className="section-index blue">02 <span>DISCOVER USA</span></div><a className="all-link" href="#discover">모든 여행지 보기 <span>＋</span></a></div><div className="destination-grid">{[['그랜드 서클','위대한 자연의 시간','ARIZONA · UTAH',pics.canyon],['뉴욕','다채로운 에너지의 도시','NEW YORK',pics.city],['캘리포니아','열정이 넘치는 라이프스타일','CALIFORNIA',pics.california],['내슈빌','음악이 흐르는 도시','TENNESSEE',pics.nashville]].map(([title,sub,state,bg])=><article className="destination" style={{backgroundImage:`linear-gradient(0deg,rgba(7,21,41,.87),transparent 65%),url(${bg})`}} key={title}><div className="card-copy"><h3>{title}</h3><p>{sub}</p><small>{state}</small></div><ArrowRight/></article>)}</div></section>
<section className="members" id="members"><div className="section-head"><div className="section-index white">03 <span>OUR MEMBERS</span></div><a className="all-link white-link" href="#contact">전체 회원사 보기 <span>＋</span></a></div><div className="member-grid">{members.map(m=><div key={m}>{m}</div>)}</div><p className="member-note">* 회원사는 가나다 순입니다.</p></section>
<section className="news section" id="news"><div className="section-head"><div className="section-index red">04 <span>NEWSROOM</span></div><a className="all-link" href="#news">뉴스룸 전체 보기 <span>＋</span></a></div><div className="news-grid">{[['INSIGHT','2024.05.20','2024 미국 여행 트렌드 리포트 한국인 여행자 데이터 분석',pics.news1],['REPORT','2024.05.14','미국 주요 관광청 최신 소식 5월 업데이트',pics.news2],['STORY','2024.05.07','미국 도로 여행의 매력 자유와 발견의 여정',pics.news3],['INDUSTRY','2024.04.29','한미 관광 협력 포럼 성료 지속 가능한 파트너십 논의',pics.news4]].map(([tag,date,title,bg])=><article className="news-card" key={title}><div className="news-image" style={{backgroundImage:`url(${bg})`}}/><div className="news-meta"><span>{tag}</span><time>{date}</time></div><h3>{title}</h3><ArrowRight/></article>)}</div></section>
<section className="cta" id="business"><div><h2>함께 연결하고,<br/>더 큰 가능성을 만듭니다.</h2><p>VUSAC와 함께 미국 여행의 미래를 만들어가세요.</p></div><div className="cta-contact"><b>CONTACT US</b><span>02-776-0560 (대표)</span><span>info@vusackorea.org</span><small>서울특별시 중구 세종대로 39<br/>대한서울상공회의소 17층</small></div><a className="contact-button" href="mailto:info@vusackorea.org">문의하기 <ArrowRight/></a></section></main>
<footer><Logo/><span>© 2024 Visit USA Committee Korea. All Rights Reserved.</span><div><a href="#contact">개인정보처리방침</a><i/><a href="#contact">이용약관</a></div></footer></div>}
createRoot(document.getElementById('root')).render(<App/>);
